version: "3"
services:
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    ports:
      - "8092:8080"
    command: ash -c "cd /home/node/app && npm i && node index.js"